server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# create mysql database connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_bookshop?useSSL=false
    username: hamit
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true